services:

  db:
    image: postgres:17-alpine    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tenancy_user
      - POSTGRES_PASSWORD=tenancy_password
      - POSTGRES_DB=tenancy_db

volumes:
  postgres_data: